### PR TITLE
Fix merge

### LINKED ISSUE #55: Argument precedence of Record and Builder merging
I've noticed that the `merge`-like functions in 'Record' favor their first argument, whereas those in 'Record.Builder' favor their second. I'm guessing that a user would at least initially assume that Record merging and Builder merging would have identical semantics except for the function/Builder difference. Could this semantic distinction and its rationale be documented? Alternatively, could either Record merging or Builder merging be updated so that the two function sets are consistent with each other? (As far as I can tell, there's no pressing problem motivating this change, but consistency is often good for its own sake, and it might help to improve grokkability and to prevent merger-precedence bugs.)

```purescript
-- Record
merge
  :: forall r1 r2 r3 r4
   . Union r1 r2 r3
  => Nub r3 r4
  => Record r1
  -> Record r2
  -> Record r4
merge l r = runFn2 unsafeUnionFn l r
```
```purescript
-- Record.Builder
merge
  :: forall r1 r2 r3 r4
   . Row.Union r1 r2 r3
  => Row.Nub r3 r4
  => Record r2
  -> Builder (Record r1) (Record r4)
merge r2 = Builder \r1 -> runFn2 unsafeUnionFn r1 r2
```

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #55

### CODE REVIEW

**Comment by JordanMartinez** [comment]
I'm not sure what should be changed in the docs for `Builder.merge`

**Comment by kl0tl** [comment]
I may have misunderstood but wasn’t the issue talking about renaming Record.Builder.merge to Record.Builder.withDefaults and adding a Record.Builder.merge function behaving like Record.merge?

**Comment by JordanMartinez** [comment]
Based on [Harry's comment here](https://github.com/purescript/purescript-record/issues/55#issuecomment-506345077), I don't think so. Seems like `Record.merge` would be renamed and `Builder.merge` should override values that exist in the original one (or something).

**Comment by hdgarrood** [comment]
@kl0tl has it right. Nothing in `Record` should be changing here.

**Comment by JordanMartinez** [comment]
Ok. I'll close this and let someone else take care of it.

**Pull request closed without merging**
